name: tag action
description: tag action
author: tdesign
inputs:
  token:
    description: Token
    required: true
  version_file:
    description: 获取版本的文件
    required: false
outputs:
  version:
    description: 版本号
  laster_tag:
    description: 最后一个标签号
runs:
  using: node20
  main: dist/index.js
