name: PR_COMMENT_CI

on:
  issue_comment:
    types: [created]
 

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      next_action: ${{ steps.get-action.outputs.next_action }}
    if: ${{ github.event.issue.pull_request }}
    steps:
       - uses: actions/checkout@v4
         with:
          fetch-depth: 1
       - uses: actions/github-script@v7
         id: get-action
         with:
          script: |
            const user = context.payload.comment.user.login
            core.debug(`user: ${user}`)

            let isReviewer = false;
            if ('liweijie0812' === `${user}`) {
                isReviewer = true
            }

            let next_action = ''  
            if (isReviewer) {
              const body = context.payload.comment.body
              core.info(`body: ${body}`)
              if (body.startsWith('/update-common')) {
                next_action='update-common'
              }
              if (body.startsWith('/test-common')) {
                next_action='test-common'
              }
              if (body.startsWith('/help')) {
                next_action='help'
              }      
            } else {
               core.warning('You are not collaborator');
            }
            core.info(`next_action: ${next_action}`)
            core.setOutput('next_action', next_action)

            
  test-common:
    needs: check
    runs-on: ubuntu-latest
    if: ${{ needs.check.outputs.next_action == 'test-common' }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: gh checkout pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.issue.number }} --recurse-submodules
      - run: git diff src/_common   
      - run: git submodule update --remote --merge
      - run: git diff src/_common

  update-common:
    needs: check
    runs-on: ubuntu-latest
    if: ${{ needs.check.outputs.next_action == 'update-common' }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: gh checkout pr
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: gh pr checkout ${{ github.event.issue.number }} --recurse-submodules 
      - run: git submodule update --remote --merge
      - name: Commit Snapshot
        run: |
          git add .
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "chore: update common"
          git push

  help:
    needs: check
    runs-on: ubuntu-latest
    if: ${{ needs.check.outputs.next_action == 'help' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs')
            const doc = fs.readFileSync('.github/pr-common-ci.md', 'utf8')
            await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: doc,
            })
