name: tag action

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
jobs:
  defatul:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: liweijie0812/test-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: liweijie0812/test-action@main
        id: tag-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          version_file: ./test/fixtures/version/package.json
      - run: echo "${{ steps.tag-action.outputs.version }}"

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: liweijie0812/test-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}     
          version_file: ./test/fixtures/version/pubspec.yaml         
